### ISSUE TITLE
what role does "ModelMode" play?

### ISSUE THREAD

**Issue by xiaominli1020** [MasterHow/PanoFlow#5]
hi,  what role does "ModelMode" play in the following code?
https://github.com/MasterHow/PanoFlow/blob/8e2f3f96335d540c97aaca480a51bcaa6cbab66a/opticalflow/core/model/base_model.py#L15
I wanna train your code, I set args.train=True, but I do not know the role of ModelMode.TEST or ModelMode.TRAIN.

**Comment by MasterHow** [comment]
It seems that this is a redundant item. We will consider removing some redundant settings in future PRs.
