### ISSUE TITLE
Could you please upload the pre-trained model to Google Drive?

### ISSUE THREAD

**Issue by ice485** [MasterHow/PanoFlow#6]
I would like to download the pre-trained model, but I do not have a WeChat account. 
Could you please upload it to Google Drive?

Thank you for publishing your excellent code.

**Comment by Sohamsingh2002** [comment]
@MasterHow could you make pre-trained model available  to download on google drive .The provided link needs WeChat/QQ account to download it which I am unable to make .

**Comment by MasterHow** [comment]
Of course! The pretrianed model are available on Google Drives now: https://drive.google.com/drive/folders/1Li3PpkjmxYWL4tdkY_tR8wOfOC9YmJE2?usp=sharing
